### ISSUE TITLE
Mobile: Various Issues

### ISSUE THREAD

**Issue by kylemh** [BlackrockDigital/startbootstrap-scrolling-nav#11]
<h3>Usually issues should have separate tickets, but all of these issues are likely in the same scope. Will create separate issues if requested to do so.</h3>

<br>

<em>Using iPhone 6S with latest OS.</em>

<br>

<b>1. Hamburger Button fails to change to 'not selected' state</b>

Steps to recreate issue:
<ol>
<li>Click hamburger button</li>
<li>Click hamburger button again and see that button stays "selected"</li>
</ol>

Note: If you select one of the sections from the drop-down menu, the hamburger button becomes "unselected".

<br>

<b>2. Drop-down menu fails to hide after selecting section</b>

Steps to recreate issue:
<ol>
<li>Click hamburger button</li>
<li>Select 'About', 'Services', or 'Contact'</li>
</ol>

<br>

<b>3. 'Logo' stays highlighted unless another <a> is selected</b>

Steps to recreate issue:
<ol>
<li>Select 'Start Bootstrap'</li>
<li>Slide vertically to new section</li>
</ol>
<em>Alternatively...</em>
<ol>
<li>Select hamburger button</li>
<li>Select logo</li>
<li>Do anything except tap another <a> item</li>
</ol>

<br>
<br>

<h4>I'd 3 is super tertiary, but the first two aspects of this issue are problematic.</h4>

**Comment by crashspringfield** [comment]
My page becomes a clusterfuck in mobile view. When I size the window down, the different sections stack on top of one another.

I tried adjusting the height and padding in the CSS file, using %, px, and em, but it doesn't make a difference.

**Comment by kylemh** [comment]
This bug is actually present in all bootstrap themes. This has nothing to do with BlackrockDigital - I've closed the issue.
