### ISSUE TITLE
Change active state if the page is 50px from top

### ISSUE THREAD

**Issue by Santoshah** [BlackrockDigital/startbootstrap-scrolling-nav#19]
I am trying to stop the div when it reaches `50px` from the top. It works while I made the change on `scrollTop: $($anchor.attr('href')).offset().top - 50` but the active state on navigation doesn't change. It only change if I scroll that `50px`  too. Please help.

**Comment by davidtmiller** [comment]
The scrollspy and the smooth scrolling feature both have offsets. They're now both set to 54 by default and you can change them in the `scrolling-nav.js` file.
