### ISSUE TITLE
scrolling not working

### ISSUE THREAD

**Issue by TwinkleThomas** [BlackrockDigital/startbootstrap-scrolling-nav#3]
Smooth scrolling not working

**Comment by davidtmiller** [comment]
It looks like the scrolling is working in the example. What is the issue you're having?

**Comment by TwinkleThomas** [comment]
navigation working perfect but smooth scrolling not working for me.i  did all thing like example , still have problem

**Comment by TwinkleThomas** [comment]
issue solved .the problem was jquery-1.7.1.js override the existing jquery.Great Work Bro Thanks :)
