### ISSUE TITLE
100% height of section using bootstrap 4

### ISSUE THREAD

**Issue by Larraine** [BlackrockDigital/startbootstrap-scrolling-nav#30]
I cannot get the 100% height to work in a section, this worked brilliantly using the previous version of bootstrap but I cannot get the 1005 height to be the height of the browser window.

**Comment by eddyekofo94** [comment]
@Larraine me too, they're overlapping

**Comment by davidtmiller** [comment]
Try using 100vh and setting a minimum height in pixels, em, or rem - that should do the trick!
