### ISSUE TITLE
second link clicked 1st gets shown as active

### ISSUE THREAD

**Issue by jbiddulph** [BlackrockDigital/startbootstrap-scrolling-nav#49]
When I click on my first menu link it doesn't show as being active but when I click on my second menu link the first shows as active, can anyone help please?

**Comment by davidtmiller** [comment]
You may need to adjust the values in the `scrolling-nav.js` file. The scrollspy function is what is causing the active state to appear on menu items when a certain point on the page is reached. These active states have an offset as well, which is set to 56px by default. You can tweak that offset value on line 26 to change when the navbar items become active!
