### ISSUE TITLE
Flickering after click to #page-top when page's top

### ISSUE THREAD

**Issue by martinsifra** [BlackrockDigital/startbootstrap-scrolling-nav#6]
Whan you are on the top of the page and click to link with `href="#page-top"` and then scroll, the page jumps few scrolls around top position. After that scolling start correctly.

Edit: This problem occurs on the top of every position. So when you are on the #intro for example and click to `href="#intro"` and try to scroll, the page is not scrolling for some firsts wheel scrolls.

**Comment by davidtmiller** [comment]
I am not sure what I can do about this, it looks like it's a browser issue rather than the template. Sometimes in Chrome I will get some flickering, but rarely in Firefox or IE. Closing this for now.
