### ISSUE TITLE
Scrolling not in a good section

### ISSUE THREAD

**Issue by miche7** [BlackrockDigital/startbootstrap-scrolling-nav#60]
Hi,

First all, I'm really happy to use your demo ! Very nice.

But I have a problem, when I go to "Services" the hightlighting item is "About" yet.
How to solve the problem ?

Thank you very much

Michemiche

**Comment by davidtmiller** [comment]
Check the offset of the scrollspy in Bootstrap

**Comment by miche7** [comment]
:+1:
