### ISSUE TITLE
How to change navbar background color..?

### ISSUE THREAD

**Issue by panatapattu** [BlackrockDigital/startbootstrap-scrolling-nav#8]
This is perfect and I am using it in my project.

But I need to change the navbar background color to different one. How can I do it in a good way using this..?

**Comment by stanleynguyen** [comment]
This is for the animation only. All aesthetic changes should be made on your css sheet

**Comment by zzm88** [comment]
I think the best way to modify css is using Chrome Workspace.

**Comment by renishkeraliya** [comment]
how can i add more div in about section??
i can add two div in about section and when i add third div in about section then its background color are given me white not #eee so plz solve my issue

**Comment by bill10** [comment]
I have a similar question and it is related to scrolling. How to have a different nav bar color for the intro section than the rest of the sections? thank you!

**Comment by davidtmiller** [comment]
Check out the Bootstrap 4 docs at http://getbootstrap.com and you should see information on how to change the background color of the navigation.
